apiVersion: 1

datasources:

  - name: Prometheus

    type: prometheus

    access: proxy

    url: http://prometheus-server.default.svc.cluster.local

    isDefault: true

    editable: true

    uid: prometheus

    jsonData:

      httpMethod: POST

      timeInterval: 15s

      manageAlerts: true