apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Ensure this matches the exact name of your Prometheus service and namespace
    url: http://prometheus-server.monitoring.svc.cluster.local:9090
    isDefault: true
    editable: true
    uid: prometheus
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      manageAlerts: true