apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-clone
  namespace: youtube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube
  template:
    metadata:
      labels:
        app: youtube
    spec:
      containers:
        - name: youtube-clone
          image: youtube-clone:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80